### ISSUE TITLE
MIQ Website updated (Calendar view) 

### ISSUE THREAD

**Issue by deepufo** [jvolker/miq-nz-booking-tools#101] opened 2021-07-28 22:47 UTC
**Describe the bug**
<MIQ Website updated, and has broken this application in the process.>

**To Reproduce**
<Log in, click select, and the view no longer shows just the current month/calendar, but a table will all months.
It's still using the SUPER LAME, light grey dates, and marginally lighter available dates, (you have to wonder where these "students" learnt their coding, (or common sense)), but at least they now have a circle/cross overlay icon on the dates.

But really, what happened to ergonomics, let alone ignorance to laws that protect the disabled, (visually challenged), let alone those with physical handicaps. Whatever the tax payer paid for this website, and the project manager, it was too much if they did it for free).
-->

**Expected behavior**

**Screenshots**
<
![6102855e](https://user-images.githubusercontent.com/88116906/127405967-5b36a1b9-5733-4fb8-93fe-ed7123e11d61.jpg)
>

**Your system (please complete the following information):**
 - Operating System: <Windows 10>
 - Version: <21H1>

**Comment by jvolker** [comment] 2021-07-28 22:56
Duplicate of #99

**Closed as completed by jvolker** 2021-07-28 22:56 UTC
