### ISSUE TITLE
This Bot stopped giving any slot

### ISSUE THREAD

**Issue by Salvinder** [jvolker/miq-nz-booking-tools#129] opened 2021-08-18 06:12 UTC
Hi Dev,

I have joined a Discord channel which was also giving the notifications about new slots available and after 8:00am IST 17 August it stopped sending any alerts and this same happened with this bot. Developer who created Bot to give alert on discord have updated his bot at around 2:00am IST 18 August and we are now getting alerts of spaces. Can this bot also be updated? As its not possible to book a seat after getting a alert. Its a game of milliseconds.

Here is the link of Channel - https://discord.gg/nSUtFgD7
You can find chat in General chat window.

**Comment by cmartin-kavlifoundation** [comment] 2021-08-18 07:21
This is a duplicate of issue #127 and there is a proposed pull request there that will hopefully fix it.

**Comment by Salvinder** [comment] 2021-08-18 07:37
Thanks for the update!

**Comment by monagjr** [comment] 2021-08-19 15:54
Anyone who needs ready-made pre-built version of the APP latest version (v0.10.4):

https://github.com/monagjr/miq-nz-booking-tools/releases/latest

-----
https://www.buymeacoffee.com/mojr

**Comment by Salvinder** [comment] 2021-08-19 16:15
Thank you!!!

**Comment by cummins070** [comment] 2021-08-20 13:54
> Anyone who needs ready-made pre-built version of the APP latest version (v0.10.4):
> 
> https://github.com/monagjr/miq-nz-booking-tools/releases/latest
> 
> https://www.buymeacoffee.com/mojr

Donation made thanks for updating!

**Comment by monagjr** [comment] 2021-08-20 15:20
thanks @cummins070 . much appreciated :)

**Comment by jvolker** [comment] 2021-08-22 11:12
Fixed in latest release: https://github.com/jvolker/miq-nz-booking-tools/releases/latest

Thanks to @monagjr

**Closed as completed by jvolker** 2021-08-22 11:12 UTC
