### ISSUE TITLE
MIQ Booking Page has changed again

### ISSUE THREAD

**Issue by Mya-Rose** [jvolker/miq-nz-booking-tools#100] opened 2021-07-28 22:31 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your system (please complete the following information):**
 - Operating System: 
 - Version:

**Comment by HKG2301** [comment] 2021-07-28 22:49
Yup, another calendar format change, and it stops the script running again it seems...
![image_2021-07-29_104812](https://user-images.githubusercontent.com/87677692/127406030-28e541b9-1298-460a-a57d-9404e53f3882.png)

**Comment by jvolker** [comment] 2021-07-28 22:55
Duplicate of #99

**Closed as completed by jvolker** 2021-07-28 22:55 UTC
